name: "ensemble_yolo"
platform: "ensemble"
max_batch_size: 32
input [ { name: "INPUT", data_type: TYPE_FP32, dims: [ -1 ] } ]
output [ { name: "OUTPUT", data_type: TYPE_FP32, dims: [ 5 ] } ]
ensemble_scheduling {
  step [
    {
      model_name: "preprocess"
      model_version: -1
      input_map { key: "raw_image", value: "INPUT" }
      output_map { key: "processed_image", value: "preprocessed_tensor" }
    },
    {
      model_name: "yolo_ensemble"
      model_version: -1
      input_map { key: "images", value: "preprocessed_tensor" }
      output_map { key: "output0", value: "yolo_raw_tensor" }
    },
    {
      model_name: "postprocess"
      model_version: -1
      input_map { key: "yolo_output", value: "yolo_raw_tensor" }
      output_map { key: "final_output", value: "OUTPUT" }
    }
  ]
}
