name: "preprocess"
backend: "python"
max_batch_size: 32
input [ { name: "raw_image", data_type: TYPE_FP32, dims: [ -1 ] } ]
output [ { name: "processed_image", data_type: TYPE_FP32, dims: [ 3, 640, 640 ] } ]
